DROP TABLE IF EXISTS ACHIEVEMENTS;
DROP TABLE IF EXISTS BADGES;
DROP TABLE IF EXISTS INTERACTIONS;
DROP TABLE IF EXISTS FRIENDS;
DROP TABLE IF EXISTS HABITLOGS;
DROP TABLE IF EXISTS Habits;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    SCORES INT NOT NULL DEFAULT 0,
    LEVEL INT NOT NULL DEFAULT 1
);

CREATE TABLE Habits(
    HabitID INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT NOT NULL,
    HabitName VARCHAR(100) NOT NULL,
    Frequency VARCHAR(20) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE HABITLOGS(
    LOGID INT PRIMARY KEY AUTO_INCREMENT,
    HABITID INT NOT NULL,
    DATE DATE NOT NULL,
    COMPLETED BOOLEAN NOT NULL,
    FOREIGN KEY (HABITID) REFERENCES Habits(HabitID)
);

CREATE TABLE FRIENDS(
    FRIENDSHIPID INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT NOT NULL,
    FRIENDID INT NOT NULL,
    UNIQUE(USERID, FRIENDID),
    FOREIGN KEY (USERID) REFERENCES Users(UserID),
    FOREIGN KEY (FRIENDID) REFERENCES Users(UserID)
);

CREATE TABLE INTERACTIONS(
    INTERACTIONID INT PRIMARY KEY AUTO_INCREMENT,
    FRIENDSHIPID INT NOT NULL,
    INTERACTIONTYPE ENUM('Motivation','Shared','Milestone') NOT NULL,
    INTERACTIONSTEP VARCHAR(255) NOT NULL,
    FOREIGN KEY (FRIENDSHIPID) REFERENCES FRIENDS(FRIENDSHIPID)
);

CREATE TABLE BADGES(
    BADGEID INT PRIMARY KEY AUTO_INCREMENT,
    BADGENAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE ACHIEVEMENTS(
    ACHIEVEMENTID INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT NOT NULL,
    BADGEID INT NOT NULL,
    FOREIGN KEY (USERID) REFERENCES Users(UserID),
    FOREIGN KEY (BADGEID) REFERENCES BADGES(BADGEID)
);





